/**
 * Industry types used in Google Places request.
 */
export const INDUSTRY_TYPES = {
  CULTURE: [
    'art_gallery',
    'art_studio',
    'cultural_landmark',
    'historical_place',
    'monument',
    'museum',
  ],
  ENTERTAINMENT_AND_RECREATION: [
    'amusement_center',
    'amusement_park',
    'aquarium',
    'casino',
    'comedy_club',
    'dance_hall',
    'event_venue',
    'ferris_wheel',
    'garden',
    'hiking_area',
    'historical_landmark',
    'karaoke',
    'national_park',
    'night_club',
    'observation_deck',
    'opera_house',
    'park',
    'planetarium',
    'plaza',
    'roller_coaster',
    'state_park',
    'tourist_attraction',
    'zoo',
  ],
  FOOD_AND_DRINK: [
    'bakery',
    'bar',
    'cafe',
    'coffee_shop',
    'food_court',
    'ice_cream_shop',
    'pub',
    'restaurant',
    'sandwich_shop',
    'steak_house',
    'tea_house',
    'wine_bar',
  ],
  LODGING: [
    'bed_and_breakfast',
    'hostel',
    'hotel',
    'inn',
    'lodging',
    'motel',
    'resort_hotel',
  ],
  SHOPPING: [
    'book_store',
    'clothing_store',
    'convenience_store',
    'department_store',
    'discount_store',
    'electronics_store',
    'gift_shop',
    'home_goods_store',
    'jewelry_store',
    'market',
    'shopping_mall',
    'store',
    'supermarket',
  ],
  TRANSPORTATION: [
    'airport',
    'bus_station',
    'bus_stop',
    'ferry_terminal',
    'subway_station',
    'taxi_stand',
    'train_station',
    'transit_depot',
    'transit_station',
  ],
};
